_target_: pli_cyto.models.dft_style.DFTStyleLitModule
lr: 1e-3
angles: [
  -7.5, -7.0, -6.5, -6.0, -5.5, -5.0, -4.5, -4.0, -3.5,
  -3.0, -2.5, -2.0, -1.5, -1.0, -0.5, 0.0, 0.5, 1.0, 1.5,
  2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 6.5, 7.0, 7.5,
]
cyto_patch_size: ${datamodule.cyto_patch_size}
pli_patch_size: ${datamodule.pli_patch_size}
min_overlap: 0.9999  # Min overlap of 256 x 256 (minus a bit for stability)
keep_best: -1
out_channels: ${datamodule.channels}
rec_loss: mae_loss
style_loss: masked_gram
equivariant_loss: mse_loss
layer_weights: [1.0, 1.0, 1.0, 1.0, 1.0]
style_loss_weight: 5_000.0
rec_loss_weight: 0.5
equivariant_loss_weight: 0.1
register_target: True
registration_method: mse

style_net:
  _target_: pli_cyto.models.components.style.VGGStyle
  name: vgg19
  weights: imagenet
  depth: 4
  in_channels: ${datamodule.channels}

gen:
  _target_: pli_cyto.models.components.generator.PLIUnet
  enc_channels: [32, 64, 128, 256, 512]
  dec_channels: [512, 256, 128, 64, 32]
  n_classes: 3
  activation: sigmoid
